version: 2
# log-file: /tmp/efm-langserver.log 
# log-level: 1
root-markers:
  - .git/
lint-debounce: 1s

tools:
  shellcheck: &shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  eslint: &eslint
    lint-command: bash $HOME/.config/efm-langserver/eslint-stdin.sh ${INPUT}
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %trror %m"
      - "%f(%l,%c): %tnfo %m"
    # format-command: bash $HOME/.config/efm-langserver/eslint-format-stdin.sh ${INPUT}
    # format-stdin: true
    root-markers:
      - .eslintrc.cjs
      - .eslintrc.js
      - .eslintrc.json

  prettier: &prettier
    format-command: 'npx --no-install prettier --stdin-filepath ${INPUT}'
    format-stdin: true
    root-markers:
      - .prettierrc.json

  terraform: &terraform
    format-command: terraform fmt -
    format-stdin: true

  goimports: &goimports
    format-command: goimports
    format-stdin: true

languages:
  sh:
    - <<: *shellcheck

  javascript:
    - <<: *prettier
    - <<: *eslint

  typescript:
    - <<: *prettier
    - <<: *eslint

  javascriptreact:
    - <<: *prettier
    - <<: *eslint

  typescriptreact:
    - <<: *prettier
    - <<: *eslint

  terraform:
    - <<: *terraform

  go:
    - <<: *goimports
