version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  shellcheck: &shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  eslint: &eslint
    lint-command: 'npx --no-install eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    format-command: npx --no-install eslint -f json --stdin --fix-dry-run --stdin-filename ${INPUT} | jq -e -r '.[0].output | rtrimstr("\n")'
    format-stdin: true

  # prettier: &prettier
  #   format-command: 'npx --no-install prettier --stdin-filepath ${INPUT}'
  #   format-stdin: true

languages:
  sh:
    - <<: *shellcheck

  javascript:
    - <<: *eslint

  typescript:
    - <<: *eslint

  javascriptreact:
    - <<: *eslint

  typescriptreact:
    - <<: *eslint
